# Tensor
在深度学习中，我们通常会频繁地对数据进行操作。作为动手学深度学习的基础，本节将介绍如何对内存中的数据进行操作。

在PyTorch中，torch.Tensor是存储和变换数据的主要工具。如果你之前用过NumPy，你会发现Tensor和NumPy的多维数组非常类似。然而，Tensor提供GPU计算和自动求梯度等更多功能，这些使Tensor更加适合深度学习。

> "tensor"这个单词一般可译作“张量”，张量可以看作是一个多维数组。标量可以看作是0维张量，向量可以看作1维张量，矩阵可以看作是二维张量。

### 1、 创建Tensor


#### 1.1 直接创建
1. torch.Tensor(sizes)
2. torch.tensor(data, dtype=None, device=None,requires_grad=False)

  - data - 可以是list, tuple, numpy array, scalar或其他类型
  - dtype - 可以返回想要的tensor类型
  - device - 可以指定返回的设备
  - requires_grad - 可以指定是否进行记录图的操作，默认为False
  
**注意：torch.tensor 总是会复制 data, 如果想避免复制，可以使 data.detach()**

In [45]:
import torch

创建一个5x3的未初始化的Tensor：

In [46]:
torch.Tensor(5,3)

tensor([[9.2755e-39, 1.0561e-38, 4.5001e-39],
        [4.2246e-39, 1.0286e-38, 1.0653e-38],
        [1.0194e-38, 8.4490e-39, 1.0469e-38],
        [9.3674e-39, 9.9184e-39, 8.7245e-39],
        [9.2755e-39, 8.9082e-39, 9.9184e-39]])

创建一个5x3的未初始化的Tensor：

In [14]:
x = torch.empty(5, 3)
print(x)


tensor([[5.9803e-16, 7.8473e-43, 5.9803e-16],
        [7.8473e-43, 5.9803e-16, 7.8473e-43],
        [5.9803e-16, 7.8473e-43, 5.9803e-16],
        [7.8473e-43, 5.9803e-16, 7.8473e-43],
        [5.9803e-16, 7.8473e-43, 5.9803e-16]])


创建一个5x3的long型全0的Tensor:


In [15]:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


还可以直接根据数据创建:

In [16]:
a = torch.Tensor((5,3))
b = torch.Tensor([5,3])  # 两个结果相等
print(a,b,a==b )

tensor([5., 3.]) tensor([5., 3.]) tensor([True, True])


还可以通过现有的Tensor来创建，此方法会默认重用输入Tensor的一些属性，例如数据类型，除非自定义数据类型。

In [20]:
x = x.new_ones(5, 3, dtype=torch.float64)  # 返回的tensor默认具有相同的torch.dtype和torch.device
print(x)
x = torch.randn_like(x, dtype=torch.float) # 指定新的数据类型
print(x) 

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[-0.2424, -0.5536,  0.3723],
        [ 0.3653,  0.5084,  0.4734],
        [-0.0159, -1.2814,  1.2615],
        [ 0.3237,  0.2417, -1.2923],
        [-0.3165, -2.0940,  2.4526]])


可以通过shape或者size()来获取Tensor的形状:
> 注意：返回的torch.Size其实就是一个tuple, 支持所有tuple的操作。

In [21]:
print(x.size())
print(x.shape)

torch.Size([5, 3])
torch.Size([5, 3])


还有很多函数可以创建Tensor，去翻翻官方API就知道了，下表给了一些常用的作参考。

|函数	|功能|
| :- - -  | :- - - |
|Tensor(sizes)	| 基础构造函数|
|tensor(data,)	|类似np.array的构造函数|
|ones(sizes)	|全1Tensor|
|zeros(sizes)	|全0Tensor|
|eye(sizes)	|对角线为1，其他为0|
|arange(s,e,step)	|从s到e，步长为step|
|linspace(s,e,steps)	|从s到e，均匀切分成steps份|
|rand/randn(\*sizes)	|均匀/标准分布|
|normal(mean,std)/uniform(from,to)	|正态分布/均匀分布|
|randperm(m)	|随机排列|

*注：这些创建方法都可以在创建的时候指定数据类型dtype和存放device(cpu/gpu)。*

#### 1.2 从numpy中获得数据

**注意：这种方式会共享内存，修改numpy数据会导致tensor数据改变,而任何对tensor的操作都会影响到ndarry**

In [61]:
import numpy as np
a = np.array([1,2,3,4])
b = torch.from_numpy(a)
print(a,'\t',b)

a[3] = 5
print(a,'\t',b)

[1 2 3 4] 	 tensor([1, 2, 3, 4], dtype=torch.int32)
[1 2 3 5] 	 tensor([1, 2, 3, 5], dtype=torch.int32)


#### 1.3 创建特定的tensor

* **根据数值要求：**

In [ ]:
torch.zeros(*sizes, out=None, …)# 返回大小为sizes的零矩阵

torch.zeros_like(input, …) # 返回与input相同size的零矩阵

torch.ones(*sizes, out=None, …) #f返回大小为sizes的单位矩阵

torch.ones_like(input, …) #返回与input相同size的单位矩阵

torch.full(size, fill_value, …) #返回大小为sizes,单位值为fill_value的矩阵

torch.full_like(input, fill_value, …) 返回与input相同size，单位值为fill_value的矩阵

torch.arange(start=0, end, step=1, …) #返回从start到end, 单位步长为step的1-d tensor.

torch.linspace(start, end, steps=100, …) #返回从start到end, 间隔中的插值数目为steps的1-d tensor

torch.logspace(start, end, steps=100, …) #返回1-d tensor ，从10start到10end的steps个对数间隔

* **根据矩阵要求:**

In [ ]:
torch.eye(n, m=None, out=None,…) #返回2-D 的单位对角矩阵

torch.empty(*sizes, out=None, …) #返回被未初始化的数值填充，大小为sizes的tensor

torch.empty_like(input, …) # 返回与input相同size,并被未初始化的数值填充的tensor

* **随机采用生成:**

In [ ]:
torch.normal(mean, std, out=None)

torch.rand(*size, out=None, dtype=None, …) #返回[0,1]之间均匀分布的随机数值

torch.rand_like(input, dtype=None, …) #返回与input相同size的tensor, 填充均匀分布的随机数值

torch.randint(low=0, high, size,…) #返回均匀分布的[low,high]之间的整数随机值

torch.randint_like(input, low=0, high, dtype=None, …) #

torch.randn(*sizes, out=None, …) #返回大小为size,由均值为0，方差为1的正态分布的随机数值

torch.randn_like(input, dtype=None, …)

torch.randperm(n, out=None, dtype=torch.int64) # 返回0到n-1的数列的随机排列

### 2. 操作
本小节介绍Tensor的各种操作。

#### 2.1算术操作

* **基本运算，加减乘除**  
在PyTorch中，同一种操作可能有很多种形式，下面用加法作为例子。

* 形式一

In [25]:
x = torch.rand(5, 3)
y = torch.rand(5, 3)
print(x + y)

tensor([[1.0197, 0.7444, 1.4426],
        [1.3822, 1.3228, 0.8300],
        [0.4532, 1.4033, 1.0209],
        [1.2170, 0.2429, 0.4638],
        [1.4893, 1.6903, 1.6833]])


* 形式二

In [27]:
print(torch.add(x,y))

# 或指定输出

result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[1.0197, 0.7444, 1.4426],
        [1.3822, 1.3228, 0.8300],
        [0.4532, 1.4033, 1.0209],
        [1.2170, 0.2429, 0.4638],
        [1.4893, 1.6903, 1.6833]])
tensor([[1.0197, 0.7444, 1.4426],
        [1.3822, 1.3228, 0.8300],
        [0.4532, 1.4033, 1.0209],
        [1.2170, 0.2429, 0.4638],
        [1.4893, 1.6903, 1.6833]])


* 形式三 inplace

In [28]:
# adds x to y
y.add_(x)
print(y)

tensor([[1.0197, 0.7444, 1.4426],
        [1.3822, 1.3228, 0.8300],
        [0.4532, 1.4033, 1.0209],
        [1.2170, 0.2429, 0.4638],
        [1.4893, 1.6903, 1.6833]])


> 注：PyTorch操作inplace版本都有后缀_, 例如x.copy_(y), x.t_()

|     运算       |    Opera      |
| :---------------:  | :---------------: |
|  减 |y-x <br> torch.sub(y, x) <br> y.sub(x) <br>  y.sub_(x) |
|  元素乘 |x * y <br> torch.mul(x, y) <br> x.mul(y), <br> x.mul_(y) |
|  元素除 |x / y <br> torch.div(x, y) <br> x.div(y), <br> x.div_(y) |
|  矩阵乘 |torch.matmul(x, y.T))) <br> (m @ n)|
|  矩阵除 |torch.linalg.inv() |

**注：（对于高维的Tensor(dim>2),定义其矩阵乘法仅在最后的两个维度上,要求前面的维度必须保持一致运算操作只有torch.matmul()和@**

#### 2.2 高等运算
* **对数运算：**

In [65]:
torch.log(x, out=None)  # y_i=log_e(x_i)

torch.log1p(x, out=None)  #y_i=log_e(x_i+1)

torch.log2(x, out=None)   #y_i=log_2(x_i)

torch.log10(x,out=None)  #y_i=log_10(x_i)

tensor([[-0.8607, -0.1685,  0.0179],
        [-0.0918,  0.0662, -0.8899],
        [ 0.0332,  0.0850, -0.2049],
        [ 0.2308, -0.8082,  0.7295],
        [-0.2799,  0.1523, -0.1190]])

* **幂函数：**

In [103]:
torch.pow(x, 2, out=None)  # y_i=x^(2)

tensor([1, 4])

* **指数运算**

In [71]:
torch.exp(x, out=None)     # y_i=e^(x_i)

torch.expm1(x, out=None)   # y_i=e^(x_i) -1

tensor([[1.4776e-01, 9.7092e-01, 1.8353e+00],
        [1.2469e+00, 2.2045e+00, 1.3752e-01],
        [1.9427e+00, 2.3747e+00, 8.6615e-01],
        [4.4817e+00, 1.6826e-01, 2.1255e+02],
        [6.9036e-01, 3.1373e+00, 1.1391e+00]])

* **截断函数**

In [ ]:
torch.ceil(x, out=None)   #返回向正方向取得最小整数

torch.floor(x, out=None)  #返回向负方向取得最大整数

torch.round(x, out=None) #返回相邻最近的整数，四舍五入
torch.trunc(x, out=None) #返回整数部分数值
torch.frac(x, out=None) #返回小数部分数值

torch.fmod(x, divisor, out=None) #返回input/divisor的余数
torch.remainder(x, divisor, out=None) #同上

* **对比操作：**

In [ ]:
torch.eq(input, other, out=None)  #按成员进行等式操作，相同返回1

torch.equal(tensor1, tensor2) #如果tensor1和tensor2有相同的size和elements，则为true

torch.eq(torch.tensor([[1, 2], [3, 4]]), torch.tensor([[1, 1], [4, 4]]))

tensor([[ 1,  0],[ 0,  1]], dtype=torch.uint8)

torch.eq(torch.tensor([[1, 2], [3, 4]]), torch.tensor([[1, 1], [4, 4]]))

tensor([[ 1,  0],[ 0,  1]], dtype=torch.uint8)



torch.ge(input, other, out=None) # input>= other
torch.gt(input, other, out=None) # input>other
torch.le(input, other, out=None) # input=<other
torch.lt(input, other, out=None) # input<other
torch.ne(input, other, out=None) # input != other 不等于

In [ ]:
torch.max() # 返回最大值
torch.min() # 返回最小值
torch.isnan(tensor) #判断是否为’nan’
torch.sort(input, dim=None, descending=False, out=None) #对目标input进行排序
torch.topk(input, k, dim=None, largest=True, sorted=True, out=None) #沿着指定维度返回最大k个数值及其索引值
torch.kthvalue(input, k, dim=None, deepdim=False, out=None) #沿着指定维度返回最小k个数值及其索引值

In [ ]:
torch.dot(tensor1, tensor2) #返回tensor1和tensor2的点乘

torch.mm(mat1, mat2, out=None) #返回矩阵mat1和mat2的乘积

torch.eig(a, eigenvectors=False, out=None) #返回矩阵a的特征值/特征向量

torch.det(A) #返回矩阵A的行列式

torch.trace(input) #返回2-d 矩阵的迹(对对角元素求和)

torch.diag(input, diagonal=0, out=None) #

torch.histc(input, bins=100, min=0, max=0, out=None) #计算input的直方图

torch.tril(input, diagonal=0, out=None) #返回矩阵的下三角矩阵，其他为0

torch.triu(input, diagonal=0, out=None) #返回矩阵的上三角矩阵，其他为0

* **tensor索引**  
  **注意：索引出来的结果与原数据共享内存，也即修改一个，另一个会跟着修改。**

In [80]:
y = x[0, :]
y += 1
print(y)
print(x[0, :]) # 源tensor也被改了

tensor([1.1378, 1.6785, 2.0422])
tensor([1.1378, 1.6785, 2.0422])


除了常用的索引选择数据之外，PyTorch还提供了一些高级的选择函数:

|函数 |功能|
| :-------------: | :-------------: |
|index_select(input, dim, index)|在指定维度dim上选取，比如选取某些行、某些列|
|masked_select(input, mask)|例子如上，a[a>0]，使用ByteTensor进行选取|
|nonzero(input)|非0元素的下标|
|gather(input, dim, index)|根据index，在dim维度上选取数据，输出的size与index一样|


* **改变形状**  

  用view()来改变Tensor的形状：
  
  **注意:view()返回的新Tensor与源Tensor虽然可能有不同的size，但是是共享data的，也即更改其中的一个，另外一个也会跟着改变。(顾名思义，view仅仅是改变了对这个张量的观察角度，内部数据并未改变)**

In [77]:
y = x.view(15)
z = x.view(-1, 5)  # -1所指的维度可以根据其他维度的值推出来
print(x.size(), y.size(), z.size())

torch.Size([5, 3]) torch.Size([15]) torch.Size([3, 5])


所以如果我们想返回一个真正新的副本（即不共享data内存）该怎么办呢？Pytorch还提供了一个reshape()可以改变形状，但是此函数并不能保证返回的是其拷贝，所以不推荐使用。推荐先用clone创造一个副本然后再使用view。

* 使用clone还有一个好处是会被记录在计算图中，即梯度回传到副本时也会传到源Tensor。

In [82]:
x_cp = x.clone().view(15)
x -= 1
print(x)
print(x_cp)

tensor([[-0.8622, -0.3215,  0.0422],
        [-1.1905, -0.8354, -1.8711],
        [-0.9207, -0.7837, -1.3761],
        [-0.2986, -1.8445,  3.3639],
        [-1.4751, -0.5800, -1.2396]])
tensor([ 0.1378,  0.6785,  1.0422, -0.1905,  0.1646, -0.8711,  0.0793,  0.2163,
        -0.3761,  0.7014, -0.8445,  4.3639, -0.4751,  0.4200, -0.2396])


* **tensor 转numpy**

  * item():它可以将一个标量Tensor转换成一个Python number
  * numpy():它可以将一个多维Tensor转换成一个Python number

In [88]:
print(x)
print(torch.rand(1).item())
print(x.numpy())

tensor([[-0.8622, -0.3215,  0.0422],
        [-1.1905, -0.8354, -1.8711],
        [-0.9207, -0.7837, -1.3761],
        [-0.2986, -1.8445,  3.3639],
        [-1.4751, -0.5800, -1.2396]])
0.28911006450653076
[[-0.86218345 -0.3215015   0.04215813]
 [-1.1904652  -0.8354379  -1.8711458 ]
 [-0.9206618  -0.7836976  -1.3761202 ]
 [-0.2985927  -1.8444823   3.3638597 ]
 [-1.4750576  -0.5799607  -1.2396071 ]]


### 3、 广播机制
前面我们看到如何对两个形状相同的Tensor做按元素运算。当对两个形状不同的Tensor按元素运算时，可能会触发广播（broadcasting）机制：先适当复制元素使这两个Tensor形状相同后再按元素运算。例如：

In [89]:
x = torch.arange(1, 3).view(1, 2)
print(x)
y = torch.arange(1, 4).view(3, 1)
print(y)
print(x + y)

tensor([[1, 2]])
tensor([[1],
        [2],
        [3]])
tensor([[2, 3],
        [3, 4],
        [4, 5]])


由于x和y分别是1行2列和3行1列的矩阵，如果要计算x + y，那么x中第一行的2个元素被广播（复制）到了第二行和第三行，而y中第一列的3个元素被广播（复制）到了第二列。如此，就可以对2个3行2列的矩阵按元素相加。

### 4、运算的内存开销
索引操作是不会开辟新内存的，而像y = x + y这样的运算是会新开内存的，然后将y指向新内存。为了演示这一点，我们可以使用Python自带的id函数：如果两个实例的ID一致，那么它们所对应的内存地址相同；反之则不同。

In [91]:
x = torch.tensor([1, 2])
y = torch.tensor([3, 4])
id_before = id(y)
y = y + x
print(id(y) == id_before) # False 

False


如果想指定结果到原来的y的内存，我们可以使用前面介绍的索引来进行替换操作。在下面的例子中，我们把x + y的结果通过[:]写进y对应的内存中。

In [92]:
x = torch.tensor([1, 2])
y = torch.tensor([3, 4])
id_before = id(y)
y[:] = y + x
print(id(y) == id_before) # True

True


我们还可以使用运算符全名函数中的out参数或者自加运算符+=(也即add_())达到上述效果，例如torch.add(x, y, out=y)和y += x(y.add_(x))。

In [94]:
x = torch.tensor([1, 2])
y = torch.tensor([3, 4])
id_before = id(y)
torch.add(x, y, out=y) # y += x, y.add_(x)
print(id(y) == id_before) # True

True


> 注：虽然view返回的Tensor与源Tensor是共享data的，但是依然是一个新的Tensor（因为Tensor除了包含data外还有一些其他属性），二者id（内存地址）并不一致。

### 5、 Tensor和NumPy相互转换
我们很容易用numpy()和from_numpy()将Tensor和NumPy中的数组相互转换。但是需要注意的一点是： 这两个函数所产生的的Tensor和NumPy中的数组共享相同的内存（所以他们之间的转换很快），改变其中一个时另一个也会改变！！！

> 还有一个常用的将NumPy中的array转换成Tensor的方法就是torch.tensor(), 需要注意的是，此方法总是会进行数据拷贝（就会消耗更多的时间和空间），所以返回的Tensor和原来的数据不再共享内存。

所有在CPU上的Tensor（除了CharTensor）都支持与NumPy数组相互转换。


### 6、Tensor on GPU
    用方法to()可以将Tensor在CPU和GPU（需要硬件支持）之间相互移动。

In [97]:
# 以下代码只有在PyTorch GPU版本上才会执行
if torch.cuda.is_available():
    device = torch.device("cuda")          # GPU
    y = torch.ones_like(x, device=device)  # 直接创建一个在GPU上的Tensor
    x = x.to(device)                       # 等价于 .to("cuda")
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))       # to()还可以同时更改数据类型

### 7、小技巧

In [ ]:
# 1.tensor设置判断:
torch.is_tensor()  #如果是pytorch的tensor类型返回true

torch.is_storage() # 如果是pytorch的storage类型返回ture

# 2.判断tensor是否为空，可以如下
a=torch.Tensor()
len(a)
# or
len(a) is 0

# 3.设置: 通过一些内置函数，可以实现对tensor的精度, 类型，print打印参数等进行设置

torch.set_default_dtype(d)  #对torch.tensor() 设置默认的浮点类型

torch.set_default_tensor_type() # 同上，对torch.tensor()设置默认的tensor类型
torch.tensor([1.2, 3]).dtype # initial default for floating point is torch.float32
torch.float32
torch.set_default_dtype(torch.float64)
torch.tensor([1.2, 3]).dtype # a new floating point tensor
torch.float64
torch.set_default_tensor_type(torch.DoubleTensor)
torch.tensor([1.2, 3]).dtype # a new floating point tensor
torch.float64

torch.get_default_dtype() #获得当前默认的浮点类型torch.dtype
torch.set_printoptions(precision=None, threshold=None, edgeitems=None, linewidth=None, profile=None）#)

                       
# tensor的一些用法：
torch.lerp(star, end, weight) : 返回结果是out= star t+ (end-start) * weight
torch.rsqrt(input) : 返回平方根的倒数
torch.mean(input) : 返回平均值
torch.std(input) : 返回标准偏差
torch.prod(input) : 返回所有元素的乘积
torch.sum(input) : 返回所有元素的之和
torch.var(input) : 返回所有元素的方差
torch.tanh(input) ：返回元素双正切的结果
torch.equal(torch.Tensor(a), torch.Tensor(b)) ：两个张量进行比较，如果相等返回true
torch.max(input)： 返回输入元素的最大值
torch.min(input) ： 返回输入元素的最小值
element_size() ：返回单个元素的字节
torch.from_numpy(obj)，利用一个numpy的array创建Tensor。注意，若obj原来是1列或者1行，无论obj是否为2维，所生成的Tensor都是一阶的，若需要2阶的Tensor，需要利用view()函数进行转换。
torch.numel(obj)，返回Tensor对象中的元素总数。
torch.ones_like(input)，返回一个全1的Tensor，其维度与input相一致
torch.cat(seq, dim)，在给定维度上对输入的张量序列进行连接操作
torch.chunk（input, chunks, dim）在给定维度(轴)上将输入张量进行分块
torch.squeeze(input)，将input中维度数值为1的维度去除。可以指定某一维度。共享input的内存
torch.unsqeeze(input, dim)，在input目前的dim维度上增加一维
torch.clamp(input, min, max)，将input的值约束在min和max之间
torch.trunc(input)，将input的小数部分舍去


### 附录

#### 解决cuda不支持torch.inverse()的难点。
参考：[pytorch实现矩阵的逆](https://blog.csdn.net/zhou_438/article/details/115355584?utm_medium=distribute.pc_aggpage_search_result.none-task-blog-2~aggregatepage~first_rank_ecpm_v1~rank_v31_ecpm-1-115355584.pc_agg_new_rank&utm_term=pytorch%E9%80%86%E7%9F%A9%E9%98%B5&spm=1000.2123.3001.4430)

背景：本来pytorch是实现了逆矩阵的函数的，1.8之前是torch.inverse()，1.8是在torch.linalg.inv()  
但是，cuda不支持逆矩阵inverse，因此onnx当然也没实现inverse,但是我们训练的模型需要移植到onnx甚至cuda就会变得很困难，甚至你想在pytorch里面使用model.half()进行半精度运算的时候，就会报错说，cuda不支持inverse

因此，只能换个思路，自己实现这个算子，使用更为常见的算子来进行替代inverse

pytorch和numpy的源码很难找到inverse的具体实现，那我可以直接改为pytorch版的


In [101]:
import torch
from torch.linalg import det
 
def cof1(M,index):
    zs = M[:index[0]-1,:index[1]-1]
    ys = M[:index[0]-1,index[1]:]
    zx = M[index[0]:,:index[1]-1]
    yx = M[index[0]:,index[1]:]
    s = torch.cat((zs,ys),axis=1)
    x = torch.cat((zx,yx),axis=1)
    return det(torch.cat((s,x),axis=0))
 
def alcof(M,index):
    return pow(-1,index[0]+index[1])*cof1(M,index)
 
def adj(M):
    result = torch.zeros((M.shape[0],M.shape[1]))
    for i in range(1,M.shape[0]+1):
        for j in range(1,M.shape[1]+1):
            result[j-1][i-1] = alcof(M,[i,j])
    return result
 
def invmat(M):
    return 1.0/det(M)*adj(M)
 
M = torch.FloatTensor([[1,2,-1],[2,3,4],[3,1,2]])
print(invmat(M))
print(torch.inverse(M))

tensor([[ 0.0800, -0.2000,  0.4400],
        [ 0.3200,  0.2000, -0.2400],
        [-0.2800,  0.2000, -0.0400]])
tensor([[ 0.0800, -0.2000,  0.4400],
        [ 0.3200,  0.2000, -0.2400],
        [-0.2800,  0.2000, -0.0400]])
