# Tensor
在深度学习中，我们通常会频繁地对数据进行操作。作为动手学深度学习的基础，本节将介绍如何对内存中的数据进行操作。

在PyTorch中，torch.Tensor是存储和变换数据的主要工具。如果你之前用过NumPy，你会发现Tensor和NumPy的多维数组非常类似。然而，Tensor提供GPU计算和自动求梯度等更多功能，这些使Tensor更加适合深度学习。

> "tensor"这个单词一般可译作“张量”，张量可以看作是一个多维数组。标量可以看作是0维张量，向量可以看作1维张量，矩阵可以看作是二维张量。

### 1、 创建Tensor
我们先介绍Tensor的最基本功能，即Tensor的创建。

首先导入PyTorch：

In [3]:
import torch

创建一个5x3的未初始化的Tensor：

In [4]:
import torch
torch.Tensor(5,3)

tensor([[ 2.4789e+14,  7.2138e+22,  1.0562e-05],
        [ 4.8997e+30,  1.6534e+19,  4.4647e+30],
        [-5.6853e+01, -8.7721e-43, -7.2344e-34],
        [ 7.8473e-43,  5.7341e-42,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00]])

In [5]:
# 加括号说明初始化(5,3)
torch.Tensor((5,3))

tensor([5., 3.])

创建一个5x3的未初始化的Tensor：

In [7]:
x = torch.empty(5, 3)
print(x)


tensor([[9.2755e-39, 8.9082e-39, 9.9184e-39],
        [8.4490e-39, 9.6429e-39, 1.0653e-38],
        [1.0469e-38, 4.2246e-39, 1.0378e-38],
        [9.6429e-39, 9.2755e-39, 9.7346e-39],
        [1.0745e-38, 1.0102e-38, 9.9184e-39]])
